- name: Hello World Sample
  hosts: all
  gather_facts: False
  roles:
     - { role: tommarshall.awscli }
  tasks:
    - name: Hello Message
      become_user: admin
      shell: "echo {{ stack_name }}"
