- name: Hello World Sample
  hosts: all
  # roles:
  #    - { role: tommarshall.awscli }
  tasks:
    - name: Hello Message
      become: true
      debug:
        msg: "Hello World! {{ stack_name }}"
