---
- name: Fuse Search Test playbook.
  hosts: all
  gather_facts: false
  no_log: false
  connection: local
  collections:
    - kubernetes.core
  tasks: 
      - name: Print Hello world
        shell: "echo Hello world!"
        
